version: '2'
services:
  ## 1 Config Servers
  config-0:
    container_name: config-0
    image: mongo:latest
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
    networks:
      - sharded_mongo
  config-1:
    container_name: config-1
    image: mongo:latest
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
    networks:
      - sharded_mongo
  ## 2 Shards, 2 replica for each shards
  shard0-0:
    image: mongo:latest
    container_name: shard0-0
    command: mongod --port 27017 --shardsvr --replSet shard0
    volumes:
      - ./scripts:/scripts
    networks:
      - sharded_mongo
  shard0-1:
    image: mongo:latest
    container_name: shard0-1
    command: mongod --port 27017 --shardsvr --replSet shard0
    volumes:
      - ./scripts:/scripts
    networks:
      - sharded_mongo
  shard1-0:
    image: mongo:latest
    container_name: shard1-0
    command: mongod --port 27017 --shardsvr --replSet shard1
    volumes:
      - ./scripts:/scripts
    networks:
      - sharded_mongo
  shard1-1:
    image: mongo:latest
    container_name: shard1-1
    command: mongod --port 27017 --shardsvr --replSet shard1
    volumes:
      - ./scripts:/scripts
    networks:
      - sharded_mongo
  ## Router
  router:
    image: mongo:latest
    container_name: mongo
    command: mongos --port 27017 --configdb configserver/config-0:27017,config-1:27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config-0
      - config-1
      - shard0-0
      - shard0-1
      - shard1-0
      - shard1-1
    networks:
      - sharded_mongo
networks:
  sharded_mongo:
